version: "3.8"

services:
  # fastapi:
  #   build: .
  #   container_name: training-service
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env.docker
  #   depends_on:
  #     - minio
  #     - redis

  # minio:
  #   image: quay.io/minio/minio
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   volumes:
  #     - minio:/data
  #   environment:
  #     - MINIO_ROOT_USER=admin
  #     - MINIO_ROOT_PASSWORD=password

  redis:
    image: 'bitnami/redis:latest'
    env_file: .env.docker
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    env_file: .env.docker
    ports:
      - 8081:8081

  # worker:
  #   image: celery-app
  #   command: /start-celeryworker
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env.docker
  #   depends_on:
  #     - redis

  # flower:
  #   image: celery-app
  #   command: /start-flower
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env.docker
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - redis
  #     - worker


networks: 
  default:

volumes:
  minio:
    name: minio-db-data
  redis:
    name: redis-data